---
# file: tasks/git.yml

- name: git - clone repositories
  with_items: "{{ hosts_git_repositories|default([]) }}"
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest|default('/dns') }}"
    umask: "022"
    key_file: "{{ item.key_file|default('~/.ssh/id_rsa') }}"
    version: "{{ item.version|default('HEAD') }}"
  ignore_errors: true
  become: yes

